name: Mark Attendance

on:
  schedule:
    - cron: '0 4 * * *'   # 9:30 AM IST
    - cron: '0 13 * * *'  # 6:30 PM IST
  workflow_dispatch:       # Allows manual triggering

jobs:
  run-attendance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Attendance Script
      run: |
        python main.py
